### ISSUE TITLE
Null output path

### ISSUE THREAD

**Issue by giannico** [SimenB/add-asset-html-webpack-plugin#39] opened 2016-11-03 20:34 UTC
I'm using this plugin with the Webpack DllReferencePlugin as a means to getting my generated DLL script/style tags into my index.html file. I already have my DLL files sitting on disk waiting to be used (the location of disk is being passed to DllReferencePlugin via context/manifest)

As a result, I don't need this plugin to output the files again to disk. As a workaround, I've just configured the "outputPath" of this plugin to match where they reside on disk anyway, so it's just overwriting them with an identical copy... but, I'm afraid these configuration variables may get out of sync over time resulting in multiple copies of the same file being placed on disk.

I understand there may be more general use cases where the output option is needed, but it seems like the DLL use case is a strong one for this plugin, so I wanted to get some feedback on this. Am I using it the wrong way - and/or is this by design?

Thanks - I'm really happy with the plugin!

**Comment by SimenB** [comment] 2016-11-03 21:18
This plugin is just meant to make sure a link to your asset (my original use case being dll files) is included in webpack's compilation and html-weback-plugin's output. It was never meant to output files on disk, just to read them and make sure they're included.

`outputPath` (if that's what your question is about) is not needed, it was added in a PR after the original release: #16

All you really need is to provide `filepath`, as can be seen in the basic example:https://github.com/SimenB/add-asset-html-webpack-plugin#basic-usage. All other options are optional

**Comment by giannico** [comment] 2016-11-03 21:29
Hi Simen, that was my expectation - this is the exact same use case I have and the documentation is very clear. I have a DLL Webpack config which writes our files to `./dist/dll`, and I have my main webpack config (with DllReferencePlugin, HtmlWebpackPlugin, AddAssetHtmlPlugin, etc.).

My confusion is, these 3 lines in my config are causing my dll's that are referenced to be written to `./dist` (so as to produce identical DLLs in both `./dist/dll` and `./dist`:

```
    new AddAssetHtmlPlugin([
      {
        filepath: root('dist', webpackDllAssets.vendor.css),
        includeSourcemap: false,
        typeOfAsset: 'css'
      },
      {
        filepath: root('dist', webpackDllAssets.polyfills.js),
        includeSourcemap: false,
        typeOfAsset: 'js'
      },
      {
        filepath: root('dist', webpackDllAssets.vendor.js),
        includeSourcemap: false,
        typeOfAsset: 'js'
      }
    ])
```

**When I comment just these three lines, I no longer have the duplicate assets being produced** in `./dist` (of course, I also lose all of the value that your plug-in adds!). As a result, I modified the lines above to include `outputPath: 'css'`, `outputPath: 'js'`, `'outputPath: 'js'`, respectively, which causes the plugin to write the files, but just overwrite the original (no duplicates produced).

Have you experienced this before? I can definitely publish an example later tonight.

**Comment by SimenB** [comment] 2016-11-03 21:40
I don't understand the issue, so please post some example code!

**Comment by giannico** [comment] 2016-11-03 22:51
Hi Simen, thanks for the help. Here's a repro:

1. git clone https://github.com/giannico/angular2-tv-tracker asset-duplicate-demo
2. cd asset-duplicate-demo
3. git checkout asset-duplicate-demo
4. npm install
5. npm run build

After the build, do an `ls -ltr dist` and an `ls -ltr dist/js`.

You'll see two duplicate JS files, one set in each directory (these are my DLLs):

* vendor.[hash].dll.js
* polyfills.[hash].dll.js

6. npm run clean
7. Open webpack.config.js
8. Commit lines 178 - 197 (the AddAssetHtmlPlugin lines)
9. npm run build

After the build, do an `ls -ltr dist` and an `ls -ltr dist/js`.

You'll see the one set of files is now gone. This leads me to believe that the AddAssetHtmlPlugin is writing that duplicate set of files to disk.

Let me know if you have any issues, or if i'm misunderstanding the situation.

**Comment by SimenB** [comment] 2016-11-12 14:03
Ok, finally got around to looking at this, sorry about the delay!

The point of this module is to add extra files into the webpack compilation context, and have `html-webpack-plugin` add them to the html file it produces. The reason the file is duplicated on disk is that webpack output all files at the in the specified `output` location.

Original use case was just for development, and I used `webpack-dev-server`, meaning that files are never output to disk, it's all in-memory. So this issue went unnoticed.

That said, it's not a bug, and it's expected behavior. This plugin adds files to the webpack context, what webpack does with it later (output to disk in your case) it doesn't bother with.

Does that answer your question? In your case I'd extract path into a variable to make sure they're always in sync, and just overwrite.

**Comment by SimenB** [comment] 2016-11-18 19:31
@giannico. Closing this, ping me if you still have questions

**Closed by SimenB** 2016-11-18 19:31 UTC
Labels: question

**Comment by giannico** [comment] 2016-11-19 02:01
Hey @SimenB, really appreciate you taking a look and confirming this for me. I set the path to be in sync like you recommended, so the extra output kind of just goes unnoticed. Thanks again for the help and sorry for the delayed response!
